### ISSUE TITLE
Pip install errors out

### ISSUE THREAD

**Issue by auslaner** [ibrahimawadhamid/wagtail_blocks#2]
Pip version = 20.0.2
python version = 3.6.5

Command to reproduce = ```pip install wagtail_blocks```

Error:
```
Collecting wagtail_blocks
  Downloading wagtail_blocks-0.6.8.tar.gz (121 kB)
     |████████████████████████████████| 121 kB 2.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/username/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9k/2q40zny90hnd5mmbq6_9r76968_wh3/T/pip-install-uy9dellc/wagtail-blocks/setup.py'"'"'; __file__='"'"'/private/var/folders/9k/2q40zny90hnd5mmbq6_9r76968_wh3/T/pip-install-uy9dellc/wagtail-blocks/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9k/2q40zny90hnd5mmbq6_9r76968_wh3/T/pip-install-uy9dellc/wagtail-blocks/pip-egg-info
         cwd: /private/var/folders/9k/2q40zny90hnd5mmbq6_9r76968_wh3/T/pip-install-uy9dellc/wagtail-blocks/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/private/var/folders/9k/2q40zny90hnd5mmbq6_9r76968_wh3/T/pip-install-uy9dellc/wagtail-blocks/setup.py", line 6, in <module>
        from pip._internal.download import PipSession
    ModuleNotFoundError: No module named 'pip._internal.download'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9k/2q40zny90hnd5mmbq6_9r76968_wh3/T/pip-install-uy9dellc/wagtail-blocks/setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by LunatikDev** [comment]
Same here with python 3.6.8

**Comment by fabienheureux** [comment]
https://github.com/pypa/pip/issues/7645

It seems like Pip internals are likely to change and should better no be used in `setup.py`
https://github.com/ibrahimawadhamid/wagtail_blocks/blob/master/setup.py#L6 

I have no experience with python packaging, but I am working on a PR to fix setup.py in order to remove Pip internal dependencies.

**Comment by fabienheureux** [comment]
@LunatikCoder @auslaner  could you please retry to install this dependency with `pip install git+git://github.com/fabienheureux/wagtail_blocks#egg=wagtail-blocks` ?

**Comment by auslaner** [comment]
@fabienheureux that works
